### ISSUE TITLE
How to set RUST_FLAGS

### ISSUE THREAD

**Issue by AlvaroMS25** [akarpovskii/build.crab#6]
Hello!, i'm using this library to build a rust project alongside a zig one, but i need to set `RUST_FLAGS` in order to compile the rust one, how can i do that?

**Comment by akarpovskii** [comment]
Hi! Do you mean `RUSTFLAGS`?

You can set the value in [`.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html) to avoid using the env variable.

Using the env variable is a bit tricky because ideally you want to add the variable to the actual [run step](https://ziglang.org/documentation/master/std/#std.Build.Step.Run.setEnvironmentVariable) which is local to [the function](https://github.com/akarpovskii/build.crab/blob/main/build.zig#L98) and is not available on the call site. But you can set the variable globally for the whole build graph:

```zig
b.graph.env_map.put("RUSTFLAGS", "flags go here") catch @panic("OOM");
```

Or set the value before running `zig build` (assuming *nix shell):
```sh
RUSTFLAGS="flags go here" zig build
```

**Comment by AlvaroMS25** [comment]
That was it, thanks!
